package com.ccm.app.ui.admin

import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.clickable
import androidx.compose.foundation.horizontalScroll
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.width
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import com.ccm.app.ui.theme.CCMText
import com.ccm.app.ui.theme.CcmMono

/**
 * Admin · 兑换码管理 —— 对齐 `AdminRedemption.tsx`（311 行）。
 *
 * ## 源码结构
 * 1. 头部：标题「兑换码管理」+ 刷新 / 生成兑换码
 * 2. 错误条
 * 3. 卡片「一键生成并复制兑换话术」（有活跃套餐时）
 *    - `grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-4 gap-2`，**最多 4 个**套餐按钮
 *    - 按钮三态：默认「{名称}（一键生成）」/ 生成中「生成中...」/ 成功「已复制到剪贴板」
 * 4. 状态统计条：4 个 `rounded-full` 徽章（未使用/已使用/已过期/已禁用 + 数量）
 * 5. 筛选行：状态下拉（`w-64` 的批次 ID 输入框）
 * 6. 表格 8 列：兑换码 / 套餐 / 状态 / 批次 / 创建时间 / 使用·过期 / 使用者 / 操作
 *    - 空数据行：`colSpan=8` + `py-8 text-center text-gray-400` 显示「无数据」
 *    - 兑换码列 `font-mono text-xs`
 *    - 批次列 `max-w-[120px] truncate`
 *    - 操作列只在 `status === 'unused'` 时显示禁用按钮
 * 7. 分页（仅 `totalPages > 1` 时）：共 N 条 + 上一页/下一页（`ChevronLeft/Right` 16px）
 * 8. 生成弹窗：`w-[480px] rounded-2xl p-6`
 *    - 未生成时：套餐下拉 + 数量/有效天数（`grid grid-cols-2 gap-3`）+ 备注 + 生成按钮
 *    - 已生成时：绿色计数 + 复制全部 + `bg-gray-50 max-h-60 font-mono` 列表
 *
 * ## 状态色（`STATUS_COLORS`）
 * | 状态 | 类 | 前景 |
 * |---|---|---|
 * | unused | `bg-green-100 text-green-600` | #16A34A |
 * | used | `bg-blue-100 text-blue-600` | #2563EB |
 * | expired | `bg-gray-100 text-gray-500` | #6B7280 |
 * | disabled | `bg-red-100 text-red-600` | #DC2626 |
 *
 * ## ⚠️ 移动端
 * `w-[480px]` **不在**移动端覆盖名单里（名单是 800/720/672/560/460/440/400/360）→
 * 弹窗在 393px 屏上**溢出**。照搬源码（零变化要求），不擅自修。
 */
@Composable
fun AdminRedemptionPage(modifier: Modifier = Modifier) {
    var statusFilter by remember { mutableStateOf("") }
    var batchFilter by remember { mutableStateOf("") }
    var page by remember { mutableStateOf(1) }
    var error by remember { mutableStateOf("") }
    var showGenerate by remember { mutableStateOf(false) }
    var generated by remember { mutableStateOf(false) }

    // 生成表单
    var genCount by remember { mutableStateOf("10") }
    var genDays by remember { mutableStateOf("90") }
    var genNote by remember { mutableStateOf("") }

    AdminPage(modifier = modifier.verticalScroll(rememberScrollState())) {
        AdminPageHeader(title = "兑换码管理") {
            AdminButton(label = "刷新", onClick = { })
            AdminButton(
                label = "生成兑换码",
                onClick = { showGenerate = true; generated = false },
                variant = AdminButtonVariant.PRIMARY,
            )
        }

        if (error.isNotEmpty()) {
            AdminErrorBar(message = error, onDismiss = { error = "" })
        }

        // ── 一键生成卡片 ────────────────────────────────────────
        AdminCard {
            Text(
                text = "一键生成并复制兑换话术",
                style = CCMText.body14.copy(
                    fontSize = AdminText.sm,
                    fontWeight = FontWeight.Medium,
                ),
                color = AdminColors.gray800,
            )
            Spacer(Modifier.height(AdminSpacing.p2))

            // `grid-cols-1 sm:grid-cols-2 xl:grid-cols-4 gap-2` → 移动端**单列**
            // ⚠️ 本机视口 393px 命中 `sm:`(≥640) 吗？—— 不命中（393 < 640）→ 单列。
            Column(verticalArrangement = Arrangement.spacedBy(AdminSpacing.p2)) {
                quickPlans.forEach { plan ->
                    Box(
                        modifier = Modifier
                            .fillMaxWidth()
                            .clip(RoundedCornerShape(7.36.dp))
                            .background(AdminColors.blue50)
                            .border(1.dp, AdminColors.blue200, RoundedCornerShape(7.36.dp))
                            .clickable { }
                            .padding(horizontal = AdminSpacing.p3, vertical = AdminSpacing.p2),
                        contentAlignment = Alignment.Center,
                    ) {
                        Text(
                            text = "${plan.name}（一键生成）",
                            style = CCMText.body14.copy(fontSize = AdminText.sm),
                            color = AdminColors.blue600,
                        )
                    }
                }
            }
            Spacer(Modifier.height(AdminSpacing.p2))
            Text(
                text = "点击后自动生成 1 条兑换码，并复制完整发送文案。",
                style = CCMText.body12.copy(fontSize = AdminText.xs),
                color = AdminColors.gray500,
            )
        }
        Spacer(Modifier.height(AdminSpacing.p4))

        // ── 状态统计条 ──────────────────────────────────────────
        Row(horizontalArrangement = Arrangement.spacedBy(AdminSpacing.gap2)) {
            AdminStatusBadge("未使用", 128, "unused")
            AdminStatusBadge("已使用", 46, "used")
            AdminStatusBadge("已过期", 12, "expired")
            AdminStatusBadge("已禁用", 3, "disabled")
        }
        Spacer(Modifier.height(AdminSpacing.p4))

        // ── 筛选行 ──────────────────────────────────────────────
        Row(horizontalArrangement = Arrangement.spacedBy(AdminSpacing.gap2)) {
            AdminSelect(
                value = statusFilter.ifEmpty { "全部状态" },
                options = listOf("全部状态", "未使用", "已使用", "已过期", "已禁用"),
                modifier = Modifier.width(110.dp),
            )
            AdminTextField(
                value = batchFilter,
                onValueChange = { batchFilter = it },
                placeholder = "批次 ID",
                modifier = Modifier.width(235.0.dp),   // w-64 = 256 × 0.92
            )
        }
        Spacer(Modifier.height(AdminSpacing.p4))

        AdminRedemptionTable()
        Spacer(Modifier.height(AdminSpacing.p4))

        // ── 分页（totalPages > 1 时）────────────────────────────
        Row(
            modifier = Modifier.fillMaxWidth(),
            horizontalArrangement = Arrangement.SpaceBetween,
            verticalAlignment = Alignment.CenterVertically,
        ) {
            Text(
                text = "共 189 条",
                style = CCMText.body14.copy(fontSize = AdminText.sm),
                color = AdminColors.gray500,
            )
            Row(
                horizontalArrangement = Arrangement.spacedBy(AdminSpacing.gap2),
                verticalAlignment = Alignment.CenterVertically,
            ) {
                AdminPagerButton("上一页", enabled = page > 1) { if (page > 1) page-- }
                Text(
                    text = "$page / 10",
                    style = CCMText.body14.copy(fontSize = AdminText.sm),
                    color = AdminColors.gray600,
                )
                AdminPagerButton("下一页", enabled = page < 10) { if (page < 10) page++ }
            }
        }
    }

    if (showGenerate) {
        AdminGenerateDialog(
            generated = generated,
            count = genCount,
            days = genDays,
            note = genNote,
            onCountChange = { genCount = it },
            onDaysChange = { genDays = it },
            onNoteChange = { genNote = it },
            onGenerate = { generated = true },
            onDismiss = { showGenerate = false },
        )
    }
}

/** 状态统计徽章 —— 对应 `<span class="text-xs px-2.5 py-1 rounded-full {STATUS_COLORS}">` */
@Composable
private fun AdminStatusBadge(label: String, count: Int, status: String) {
    val (bg, fg) = redemptionStatusColors(status)
    Box(
        modifier = Modifier
            .clip(RoundedCornerShape(50))
            .background(bg)
            .padding(horizontal = 9.2.dp, vertical = AdminSpacing.p1),   // px-2.5 py-1
    ) {
        Text(
            text = "$label $count",
            style = CCMText.body12.copy(fontSize = AdminText.xs),
            color = fg,
        )
    }
}

/** 状态 → (底色, 前景色)，对应源码 `STATUS_COLORS` */
private fun redemptionStatusColors(status: String): Pair<Color, Color> = when (status) {
    "unused" -> AdminColors.green100 to AdminColors.green600
    "used" -> AdminColors.blue100 to AdminColors.blue600
    "expired" -> AdminColors.gray100 to AdminColors.gray500
    "disabled" -> AdminColors.red100 to AdminColors.red600
    else -> AdminColors.gray100 to AdminColors.gray500
}

/** 状态 → 中文标签，对应源码 `STATUS_LABELS` */
private fun redemptionStatusLabel(status: String): String = when (status) {
    "unused" -> "未使用"
    "used" -> "已使用"
    "expired" -> "已过期"
    "disabled" -> "已禁用"
    else -> status
}

/** 分页按钮 —— 对应 `p-1.5 rounded border border-gray-200` */
@Composable
private fun AdminPagerButton(label: String, enabled: Boolean, onClick: () -> Unit) {
    Box(
        modifier = Modifier
            .clip(RoundedCornerShape(3.68.dp))
            .border(1.dp, AdminColors.gray200, RoundedCornerShape(3.68.dp))
            .clickable(enabled = enabled, onClick = onClick)
            .padding(horizontal = AdminSpacing.p2, vertical = 5.52.dp),
    ) {
        Text(
            text = label,
            style = CCMText.body14.copy(fontSize = AdminText.sm),
            color = if (enabled) AdminColors.gray400 else AdminColors.gray400.copy(alpha = 0.3f),
        )
    }
}

/** 兑换码行数据（对应源码 `interface Code`） */
internal data class RedemptionRow(
    val id: Int,
    val code: String,
    val planName: String,
    val status: String,
    val batchId: String,
    val createdAt: String,
    val usedAt: String?,
    val expiresAt: String?,
    val usedBy: String?,
)

/**
 * 兑换码表格 —— 8 列。
 *
 * ⚠️ 横向滚动包最外层（同 AdminKeyPool / AdminPlans）：
 * 每行独立滚动会导致表头与数据列错位。
 */
@Composable
private fun AdminRedemptionTable() {
    val hScroll = rememberScrollState()
    Box(
        modifier = Modifier
            .fillMaxWidth()
            .clip(RoundedCornerShape(11.04.dp))
            .background(AdminColors.white)
            .border(1.dp, AdminColors.gray200, RoundedCornerShape(11.04.dp)),
    ) {
        Column(modifier = Modifier.horizontalScroll(hScroll)) {
            Row(
                modifier = Modifier
                    .background(AdminColors.gray50)
                    .padding(horizontal = AdminSpacing.p4),
            ) {
                RedemptionCell("兑换码", header = true, width = 148.dp)
                RedemptionCell("套餐", header = true, width = 88.dp)
                RedemptionCell("状态", header = true, width = 74.dp)
                RedemptionCell("批次", header = true, width = 110.dp)
                RedemptionCell("创建时间", header = true, width = 118.dp)
                RedemptionCell("使用/过期", header = true, width = 132.dp)
                RedemptionCell("使用者", header = true, width = 92.dp)
                RedemptionCell("操作", header = true, width = 62.dp)
            }
            Box(
                modifier = Modifier
                    .fillMaxWidth()
                    .height(1.dp)
                    .background(AdminColors.gray200),
            )

            if (sampleRedemptions.isEmpty()) {
                Box(
                    modifier = Modifier.fillMaxWidth().padding(vertical = 29.44.dp),   // py-8
                    contentAlignment = Alignment.Center,
                ) {
                    Text(
                        text = "无数据",
                        style = CCMText.body14.copy(fontSize = AdminText.sm),
                        color = AdminColors.gray400,
                    )
                }
            }

            sampleRedemptions.forEach { c ->
                Row(modifier = Modifier.padding(horizontal = AdminSpacing.p4)) {
                    // 兑换码列：font-mono text-xs text-gray-700
                    Box(
                        modifier = Modifier.width(148.dp).padding(vertical = AdminSpacing.p3),
                    ) {
                        Text(
                            text = c.code,
                            style = CCMText.body12.copy(
                                fontSize = AdminText.xs,
                                fontFamily = CcmMono,
                            ),
                            color = AdminColors.gray700,
                            maxLines = 1,
                        )
                    }
                    RedemptionCell(c.planName.ifEmpty { "-" }, width = 88.dp)

                    // 状态徽章
                    Box(
                        modifier = Modifier.width(74.dp).padding(vertical = AdminSpacing.p3),
                    ) {
                        val (bg, fg) = redemptionStatusColors(c.status)
                        Box(
                            modifier = Modifier
                                .clip(RoundedCornerShape(50))
                                .background(bg)
                                .padding(horizontal = AdminSpacing.p2, vertical = 0.46.dp),
                        ) {
                            Text(
                                text = redemptionStatusLabel(c.status),
                                style = CCMText.body12.copy(fontSize = AdminText.xs),
                                color = fg,
                            )
                        }
                    }

                    // 批次：max-w-[120px] truncate（110.4 = 120 × 0.92）
                    RedemptionCell(c.batchId, width = 110.dp, small = true)
                    RedemptionCell(c.createdAt, width = 118.dp, small = true)
                    RedemptionCell(
                        text = when {
                            c.usedAt != null -> "使用 ${c.usedAt}"
                            c.expiresAt != null -> "过期 ${c.expiresAt}"
                            else -> "-"
                        },
                        width = 132.dp,
                        small = true,
                    )
                    RedemptionCell(c.usedBy ?: "-", width = 92.dp, small = true)

                    // 操作：仅 unused 显示禁用
                    Row(
                        modifier = Modifier.width(62.dp).padding(vertical = AdminSpacing.p3),
                        verticalAlignment = Alignment.CenterVertically,
                    ) {
                        if (c.status == "unused") {
                            AdminIconAction("禁用", AdminColors.gray400)
                        }
                    }
                }
                Box(
                    modifier = Modifier
                        .fillMaxWidth()
                        .height(1.dp)
                        .background(AdminColors.gray100),
                )
            }
        }
    }
}

/** 表格单元格（`px-4 py-3`；`small=true` 对应 `text-xs text-gray-400`） */
@Composable
private fun RedemptionCell(
    text: String,
    width: androidx.compose.ui.unit.Dp,
    header: Boolean = false,
    small: Boolean = false,
) {
    Box(modifier = Modifier.width(width).padding(vertical = AdminSpacing.p3)) {
        Text(
            text = text,
            style = CCMText.body14.copy(
                fontSize = when {
                    header || small -> AdminText.xs
                    else -> AdminText.sm
                },
                fontWeight = if (header) FontWeight.Medium else FontWeight.Normal,
            ),
            color = if (header) AdminColors.gray600 else AdminColors.gray400,
            maxLines = 1,
        )
    }
}

/**
 * 生成兑换码弹窗 —— 对应
 * `<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40">
 *    <div className="bg-white rounded-2xl shadow-xl w-[480px] p-6">`
 *
 * ⚠️ `w-[480px]` **不在**移动端覆盖名单 → 393px 屏上溢出。照搬源码行为。
 * `rounded-2xl` = 16 × 0.92 = **14.72**。
 */
@Composable
private fun AdminGenerateDialog(
    generated: Boolean,
    count: String,
    days: String,
    note: String,
    onCountChange: (String) -> Unit,
    onDaysChange: (String) -> Unit,
    onNoteChange: (String) -> Unit,
    onGenerate: () -> Unit,
    onDismiss: () -> Unit,
) {
    Box(
        modifier = Modifier
            // 【2026-10-06 修】原来是 fillMaxWidth —— 只定宽、高度由内容决定，
            // 于是遮罩只盖顶部一条、弹窗贴左上角（contentAlignment 在
            // 「高度=内容高度」的 Box 里等于没效果）。
            // Web 原版是 `fixed inset-0 flex items-center justify-center`（全屏）。
            .fillMaxSize()
            .background(AdminColors.black40)
            .clickable(onClick = onDismiss)
            .padding(AdminSpacing.p4),
        contentAlignment = Alignment.Center,
    ) {
        Column(
            modifier = Modifier
                .width(441.6.dp)                    // w-[480px] × 0.92（照搬溢出行为）
                .clip(RoundedCornerShape(14.72.dp)) // rounded-2xl
                .background(AdminColors.white)
                .clickable { }                      // 阻止冒泡
                .padding(AdminSpacing.p6),
        ) {
            // 标题行
            Row(
                modifier = Modifier.fillMaxWidth(),
                horizontalArrangement = Arrangement.SpaceBetween,
                verticalAlignment = Alignment.CenterVertically,
            ) {
                Text(
                    text = "生成兑换码",
                    style = CCMText.body16.copy(
                        fontSize = AdminText.base,
                        fontWeight = FontWeight.SemiBold,
                    ),
                    color = AdminColors.gray800,
                )
                Box(
                    modifier = Modifier
                        .clip(RoundedCornerShape(3.68.dp))
                        .clickable(onClick = onDismiss)
                        .padding(AdminSpacing.p1),
                ) {
                    Text(
                        text = "关闭",
                        style = CCMText.body14.copy(fontSize = AdminText.sm),
                        color = AdminColors.gray400,
                    )
                }
            }
            Spacer(Modifier.height(AdminSpacing.p4))

            if (generated) {
                // ── 已生成态 ────────────────────────────────────
                Row(
                    modifier = Modifier.fillMaxWidth(),
                    horizontalArrangement = Arrangement.SpaceBetween,
                    verticalAlignment = Alignment.CenterVertically,
                ) {
                    Text(
                        text = "已生成 10 个兑换码",
                        style = CCMText.body14.copy(fontSize = AdminText.sm),
                        color = AdminColors.green600,
                    )
                    Text(
                        text = "复制全部",
                        style = CCMText.body12.copy(fontSize = AdminText.xs),
                        color = AdminColors.blue500,
                    )
                }
                Spacer(Modifier.height(AdminSpacing.p2))
                Column(
                    modifier = Modifier
                        .fillMaxWidth()
                        .clip(RoundedCornerShape(7.36.dp))
                        .background(AdminColors.gray50)
                        .padding(AdminSpacing.p3),
                    verticalArrangement = Arrangement.spacedBy(3.68.dp),
                ) {
                    sampleRedemptions.take(4).forEach { c ->
                        Text(
                            text = c.code,
                            style = CCMText.body12.copy(
                                fontSize = AdminText.xs,
                                fontFamily = CcmMono,
                            ),
                            color = AdminColors.gray700,
                        )
                    }
                }
            } else {
                // ── 未生成态（表单）─────────────────────────────
                Text(
                    text = "套餐 *",
                    style = CCMText.body12.copy(fontSize = AdminText.xs),
                    color = AdminColors.gray500,
                )
                Spacer(Modifier.height(AdminSpacing.p1))
                AdminSelect(
                    value = quickPlans.first().name,
                    options = quickPlans.map { "${it.name} (¥${"%.2f".format(it.priceCents / 100.0)})" },
                    modifier = Modifier.fillMaxWidth(),
                )
                Spacer(Modifier.height(AdminSpacing.gap3))

                // `grid grid-cols-2 gap-3`
                Row(horizontalArrangement = Arrangement.spacedBy(AdminSpacing.gap3)) {
                    AdminLabeledField(
                        label = "数量 (1-100)",
                        value = count,
                        onValueChange = onCountChange,
                        placeholder = "10",
                        modifier = Modifier.weight(1f),
                    )
                    AdminLabeledField(
                        label = "有效天数",
                        value = days,
                        onValueChange = onDaysChange,
                        placeholder = "90",
                        modifier = Modifier.weight(1f),
                    )
                }
                Spacer(Modifier.height(AdminSpacing.gap3))
                AdminTextField(
                    value = note,
                    onValueChange = onNoteChange,
                    placeholder = "备注（可选）",
                    modifier = Modifier.fillMaxWidth(),
                )
                Spacer(Modifier.height(AdminSpacing.gap3))

                // `w-full py-2 text-sm text-white bg-blue-500 rounded-lg`
                Box(
                    modifier = Modifier
                        .fillMaxWidth()
                        .clip(RoundedCornerShape(7.36.dp))
                        .background(AdminColors.blue500)
                        .clickable(onClick = onGenerate)
                        .padding(vertical = AdminSpacing.p2),
                    contentAlignment = Alignment.Center,
                ) {
                    Text(
                        text = "生成",
                        style = CCMText.body14.copy(fontSize = AdminText.sm),
                        color = Color.White,
                    )
                }
            }
        }
    }
}

/** 演示用套餐（对应 `getPlans()` 过滤 `is_active` 后的前 4 个） */
private data class QuickPlan(val id: Int, val name: String, val priceCents: Int)

private val quickPlans = listOf(
    QuickPlan(1, "基础版", 4900),
    QuickPlan(2, "专业版", 9900),
    QuickPlan(3, "高级版", 19900),
    QuickPlan(4, "团队版", 29900),
)

/** 演示用兑换码（源码从 `getRedemptionCodes()` 拉取） */
private val sampleRedemptions = listOf(
    RedemptionRow(
        id = 1, code = "CCM-4K7P-9X2M-QW3E", planName = "基础版", status = "unused",
        batchId = "batch_20260927_a", createdAt = "2026-09-27 10:12",
        usedAt = null, expiresAt = "2026-12-26 10:12", usedBy = null,
    ),
    RedemptionRow(
        id = 2, code = "CCM-8N3R-5T1Y-ZX7C", planName = "专业版", status = "used",
        batchId = "batch_20260920_b", createdAt = "2026-09-20 08:45",
        usedAt = "2026-09-21 14:03", expiresAt = null, usedBy = "user_8823",
    ),
    RedemptionRow(
        id = 3, code = "CCM-2H9D-6V4B-LK8J", planName = "基础版", status = "expired",
        batchId = "batch_20260601_c", createdAt = "2026-06-01 00:00",
        usedAt = null, expiresAt = "2026-08-30 00:00", usedBy = null,
    ),
    RedemptionRow(
        id = 4, code = "CCM-7G5F-3S2A-PO9I", planName = "高级版", status = "disabled",
        batchId = "batch_20260901_d", createdAt = "2026-09-01 16:20",
        usedAt = null, expiresAt = "2026-11-30 16:20", usedBy = null,
    ),
)
